// <auto-generated />
using System;
using FinanceHub.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FinanceHub.Infrastructure.Migrations
{
    [DbContext(typeof(FinHubDbContext))]
    [Migration("20241012141034_HashPassword")]
    partial class HashPassword
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FinanceHub.Core.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("ec7268df-1b2c-44c5-8f90-1b31aacfacd3"),
                            Email = "admin@example.com",
                            PasswordHash = "$2a$11$WoX2aNlGJxSBeBEd9wdHe.9ORoNh8WLTCgEWmvqNaoKx3C2AnkEzm",
                            Role = "Admin",
                            Username = "admin"
                        },
                        new
                        {
                            Id = new Guid("1fad48fc-635c-4da8-a911-98bb81d402e1"),
                            Email = "user1@example.com",
                            PasswordHash = "$2a$11$wUPCnQfGB6HN6LJEwjL1Cuepd7/82UFCrAejL9PG4UqaOUvv5fTCS",
                            Role = "User",
                            Username = "user1"
                        },
                        new
                        {
                            Id = new Guid("779b75ba-a218-4292-a370-0fd208b22f54"),
                            Email = "user2@example.com",
                            PasswordHash = "$2a$11$BEKQaUpp8UI6n/KOSWaFZ.0Vwo7kch/8p9YdbiXSCpPptjfXnEh0C",
                            Role = "User",
                            Username = "user2"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
